### ISSUE TITLE
KieSession dispose 

### ISSUE THREAD

**Issue by sunurdy** [benwatson528/kafka-streams-drools#2]
https://github.com/benwatson528/kafka-streams-drools/blob/84ba32b5806ab6c26fc77431ef848ef39715e5d8/src/main/java/uk/co/hadoopathome/kafkastreams/drools/DroolsRulesApplier.java#L24

Hi, I am wondering is there a dispose function called after each session creation. 
Does it cause app memory growth if not disposing the session?

**Comment by benwatson528** [comment]
I'm afraid I haven't worked on this repo (or with Drools) in the 4 years since I made it and I never had much Drools experience to begin with. It's safe to assume that there may well be improper Drools usage here. Also note that the Drools library is now quite out of date.
